### ISSUE TITLE
Help with a variation of your code

### ISSUE THREAD

**Issue by augustodinizl** [rdehuyss/DoorDroid#1]
Hello man, i know that you even quit using that code...
But, i'm using, and it surprisingly worked well for me

but i was wondering since in my "setup", i'm using a "old" doorphone that accepts DTMF signals to drive relays...

Can you help me pointing out where/how can i put the code to send that DTMF tones to the doorphone, in the code?
Any help will be a lot appreciated
By the way, the code i'm using is here: https://github.com/augustodinizl/gensipdoor-card/blob/master/dist/gensipdoor-card.js
TIA

**Comment by rdehuyss** [comment]
To be honest, I don't know nothing about DTMF, I'm afraid...

**Comment by augustodinizl** [comment]
> To be honest, I don't know nothing about DTMF, I'm afraid...

hmmmm, ok, i saw about it in the documentation for jssip, and i was wondering if you could help me on that... but, thank you anyway... i will keep it "on hold", and i plan to follow another "path", with a "gatekeeper device" that can handle that and allow more flexibility from HA side...

But, THANK YOU for the excellent idea and work "opening the best door"...

**Comment by augustodinizl** [comment]
@rdehuyss , I got it working, with just 15 lines of code... So... Thanks for your help writing the path that made me achieve my results

**Comment by augustodinizl** [comment]
just passing by to leave you the THANKS for show the path, and to show you the code that i've used
![image](https://user-images.githubusercontent.com/25938418/126654869-8c2a7ec3-eb44-4ba7-ba9d-12e4a6c16f10.png)
https://github.com/augustodinizl/gensipdoor-card

**Comment by rdehuyss** [comment]
Thanks for the nice feedback - I'm really happy that you worked it out!
